service:
  name: orlaor-crm-server

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: lambda.handler
    events:
      - http:
          method: any
          path: /{any+}